services:
  db:
    image: postgres:17-alpine
    container_name: dev-chessbattle-db
    env_file:
      - ./backend/.env
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./backend/db/init:/docker-entrypoint-initdb.d:ro

  backend:
    build: ./backend
    container_name: dev-chessbattle-backend
    env_file: ./backend/.env
    volumes:
      - ./backend:/app
      - backend_uploads:/app/uploads
    ports:
      - "4000:4000"
      - "51212:51212"
    depends_on:
      - db

  frontend:
    build: ./frontend
    container_name: dev-chessbattle-frontend
    volumes:
      - ./frontend:/app
    ports:
      - "5173:5173"

volumes:
  db_data:
  backend_uploads:
