services:
  db:
    build:
      context: .
      dockerfile: ./docker/images/database.dockerfile
    container_name: dev-chessbattle-db
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./backend/db/init:/docker-entrypoint-initdb.d:ro

  backend:
    build:
      context: ./backend
      dockerfile: ../docker/images/backend.dev.dockerfile
    container_name: dev-chessbattle-backend
    env_file: .env
    volumes:
      - ./backend:/app
      - backend_uploads:/app/uploads
    ports:
      - "4000:4000"
      - "51212:51212"
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: ../docker/images/frontend.dev.dockerfile
    container_name: dev-chessbattle-frontend
    volumes:
      - ./frontend:/app
    ports:
      - "5173:5173"

volumes:
  db_data:
  backend_uploads:
